export const languages = ["es", "ca", "en", "fr", "de", "zh", "nl", "it"] as const;
export type Language = (typeof languages)[number];
type Copy = { nav: Record<string, string>; home: Record<string, string>; menu: Record<string, string>; contact: Record<string, string>; footer: Record<string, string> };

export const languageNames: Record<Language, string> = {
  es: "Español", ca: "Català", en: "English", fr: "Français",
  de: "Deutsch", zh: "中文", nl: "Nederlands", it: "Italiano",
};

const translations: Record<Language, Copy> = {
  es: {
    nav: { home: "Inicio", concept: "Concepto", menu: "Carta", essence: "Nuestra Esencia", contact: "Contacto", open: "Abrir menú", close: "Cerrar menú", language: "Idioma" },
    home: { title: "TR3C3 | Café de especialidad y brunch en Miami Platja", description: "El mejor café de especialidad y brunch mediterráneo de Miami Platja. Desayunos cuidados, cocina fresca y ambiente premium frente a la Costa Daurada. Te esperamos.", hero: "El café de especialidad y el brunch que enamoran Miami Platja.", lead: "Despierta con el mejor café, alarga el brunch sin mirar el reloj y siéntete como en casa frente a la Costa Daurada. Esto es TR3C3.", menuCta: "Ver la carta", mapCta: "Cómo llegar", storyTitle: "Ese sitio al que siempre quieres volver.", story: "TR3C3 nace de una obsesión: servir el mejor café de especialidad de Miami Platja, cocinar un brunch que apetezca de verdad y crear un rincón donde el tiempo va más despacio. Producto fresco, manos expertas y alma mediterránea en cada detalle.", menuTitle: "Una carta que enamora a la primera.", menuLead: "Café de especialidad, brunch irresistible y antojos dulces y salados para alargar la sobremesa.", menuFull: "Explorar la carta completa", experienceTitle: "Mucho más que una cafetería.", experience: "Desayunos sin prisa, cafés que saben a mañana perfecta y brindis que alargan la tarde. TR3C3 es el punto de encuentro de Miami Platja para sentirse bien, por dentro y por fuera.", teamTitle: "La energía que se nota en cada taza.", team: "Somos un equipo joven, profesional y enamorado de la hostelería. Nos mueve el buen café, el brunch con intención y un trato cálido que convierte cada visita en un momento para repetir.", careersTitle: "Trabaja con nosotros", careers: "¿Tienes actitud, energía y pasión por cuidar a las personas? Únete a TR3C3 y crece junto a un equipo que disfruta de lo que hace.", careersCta: "Enviar currículum", contactTitle: "Te esperamos en Miami Platja.", address: "Avinguda de Los Ángeles, 13 · 43892 Miami Platja", phone: "Teléfono — pendiente", hours: "Horario definitivo — pendiente", maps: "Abrir Google Maps", call: "Llamar", write: "Escribir" },
    menu: { title: "La carta de TR3C3", description: "Café de especialidad, bebidas frías, matcha, brunch, dulces y platos salados para compartir en Miami Platja. Descubre la carta de TR3C3.", intro: "Una carta irresistible para cualquier momento del día.", note: "Precios y disponibilidad se confirmarán en el local.", back: "Volver al inicio" },
    contact: { title: "Contacto y ubicación | TR3C3 Café & Brunch Miami Platja", description: "¿Dónde estamos y cómo llegar? Encuentra a TR3C3 en Miami Platja, reserva tu mesa y ven a vivir el mejor café de especialidad y brunch de la Costa Daurada.", heading: "Ven a conocernos.", lead: "¿Una pregunta, una reserva o ganas de descubrirnos? Estamos al otro lado, listos para recibirte.", name: "Nombre", email: "Email", message: "Mensaje", send: "Enviar consulta", formNote: "El formulario abrirá tu aplicación de correo; no almacenamos tus datos.", careers: "¿Quieres formar parte del equipo?", careersCta: "Enviar currículum" },
    footer: { line: "Café de especialidad, brunch y alma mediterránea en Miami Platja.", explore: "Navegación", work: "Trabaja con nosotros", guides: "Guías locales", rights: "Todos los derechos reservados." },
  },
  ca: {
    nav: { home: "Inici", concept: "Concepte", menu: "Carta", essence: "La Nostra Essència", contact: "Contacte", open: "Obrir menú", close: "Tancar menú", language: "Idioma" },
    home: { title: "TR3C3 | Cafè d'especialitat i brunch a Miami Platja", description: "El millor cafè d'especialitat i brunch mediterrani de Miami Platja. Esmorzars cuidats, cuina fresca i ambient premium davant la Costa Daurada. T'esperem.", hero: "El cafè d'especialitat i el brunch que enamoren Miami Platja.", lead: "Desperta amb el millor cafè, allarga el brunch sense mirar el rellotge i sent-te com a casa davant la Costa Daurada. Això és TR3C3.", menuCta: "Veure la carta", mapCta: "Com arribar", storyTitle: "Aquell lloc on sempre vols tornar.", story: "TR3C3 neix d'una obsessió: servir el millor cafè d'especialitat de Miami Platja, cuinar un brunch que vingui de gust de debò i crear un racó on el temps va més a poc a poc. Producte fresc, mans expertes i ànima mediterrània en cada detall.", menuTitle: "Una carta que enamora a la primera.", menuLead: "Cafè d'especialitat, brunch irresistible i capricis dolços i salats per allargar la sobretaula.", menuFull: "Explorar la carta completa", experienceTitle: "Molt més que una cafeteria.", experience: "Esmorzars sense pressa, cafès que saben a matí perfecte i brindis que allarguen la tarda. TR3C3 és el punt de trobada de Miami Platja per sentir-se bé, per dins i per fora.", teamTitle: "L'energia que es nota en cada tassa.", team: "Som un equip jove, professional i enamorat de l'hostaleria. Ens mou el bon cafè, el brunch amb intenció i un tracte càlid que converteix cada visita en un moment per repetir.", careersTitle: "Treballa amb nosaltres", careers: "Tens actitud, energia i passió per cuidar les persones? Uneix-te a TR3C3 i creix amb un equip que gaudeix del que fa.", careersCta: "Enviar currículum", contactTitle: "T'esperem a Miami Platja.", address: "Avinguda de Los Ángeles, 13 · 43892 Miami Platja", phone: "Telèfon — pendent", hours: "Horari definitiu — pendent", maps: "Obrir Google Maps", call: "Trucar", write: "Escriure" },
    menu: { title: "La carta de TR3C3", description: "Cafè d'especialitat, begudes fredes, matcha, brunch, dolços i plats salats per compartir a Miami Platja. Descobreix la carta de TR3C3.", intro: "Una carta irresistible per a qualsevol moment del dia.", note: "Preus i disponibilitat es confirmaran al local.", back: "Tornar a l'inici" },
    contact: { title: "Contacte i ubicació | TR3C3 Cafè & Brunch Miami Platja", description: "On som i com arribar-hi? Troba TR3C3 a Miami Platja i vine a viure el millor cafè d'especialitat i brunch de la Costa Daurada.", heading: "Vine a conèixer-nos.", lead: "Una pregunta, una reserva o ganes de descobrir-nos? Som a l'altra banda, a punt per rebre't.", name: "Nom", email: "Email", message: "Missatge", send: "Enviar consulta", formNote: "El formulari obrirà el teu correu; no emmagatzemem dades.", careers: "Vols formar part de l'equip?", careersCta: "Enviar currículum" },
    footer: { line: "Cafè d'especialitat, brunch i ànima mediterrània a Miami Platja.", explore: "Navegació", work: "Treballa amb nosaltres", guides: "Guies locals", rights: "Tots els drets reservats." },
  },
  en: {
    nav: { home: "Home", concept: "Concept", menu: "Menu", essence: "Our Essence", contact: "Contact", open: "Open menu", close: "Close menu", language: "Language" },
    home: { title: "TR3C3 | Specialty coffee and brunch in Miami Platja", description: "The best specialty coffee and Mediterranean brunch in Miami Platja. Thoughtful breakfasts, fresh cooking and a premium vibe by the Costa Daurada. Come and see.", hero: "The specialty coffee and brunch that Miami Platja falls for.", lead: "Wake up to the best coffee, let brunch run without watching the clock and feel at home by the Costa Daurada. This is TR3C3.", menuCta: "View the menu", mapCta: "Get directions", storyTitle: "The place you always want to come back to.", story: "TR3C3 begins with an obsession: to serve the best specialty coffee in Miami Platja, cook a brunch worth craving and build a corner where time slows down. Fresh produce, expert hands and Mediterranean soul in every detail.", menuTitle: "A menu you'll fall for at first sight.", menuLead: "Specialty coffee, irresistible brunch and sweet and savoury cravings to stretch lunch into the afternoon.", menuFull: "Explore the full menu", experienceTitle: "So much more than a coffee shop.", experience: "Slow breakfasts, coffees that taste like a perfect morning and toasts that stretch the afternoon. TR3C3 is the meeting point of Miami Platja to feel good, inside and out.", teamTitle: "The energy you can taste in every cup.", team: "We are a young, professional team in love with hospitality. We are driven by great coffee, brunch with intention and warm service that turns every visit into a moment worth repeating.", careersTitle: "Work with us", careers: "Got attitude, energy and a passion for looking after people? Join TR3C3 and grow with a team that loves what it does.", careersCta: "Send your CV", contactTitle: "See you in Miami Platja.", address: "Avinguda de Los Ángeles, 13 · 43892 Miami Platja", phone: "Phone — pending", hours: "Final opening hours — pending", maps: "Open Google Maps", call: "Call", write: "Email" },
    menu: { title: "The TR3C3 menu", description: "Specialty coffee, cold drinks, matcha, brunch, sweets and savoury plates to share in Miami Platja. Discover the TR3C3 menu.", intro: "An irresistible menu for every moment of the day.", note: "Prices and availability will be confirmed at the venue.", back: "Back home" },
    contact: { title: "Contact and location | TR3C3 Coffee & Brunch Miami Platja", description: "Where we are and how to reach us. Find TR3C3 in Miami Platja and come taste the best specialty coffee and brunch on the Costa Daurada.", heading: "Come and say hi.", lead: "A question, a booking or simply curious? We are right here, ready to welcome you.", name: "Name", email: "Email", message: "Message", send: "Send enquiry", formNote: "The form opens your mail app; we do not store your data.", careers: "Want to join the team?", careersCta: "Send your CV" },
    footer: { line: "Specialty coffee, brunch and Mediterranean soul in Miami Platja.", explore: "Navigation", work: "Work with us", guides: "Local guides", rights: "All rights reserved." },
  },
  fr: {
    nav: { home: "Accueil", concept: "Concept", menu: "Carte", essence: "Notre Essence", contact: "Contact", open: "Ouvrir le menu", close: "Fermer le menu", language: "Langue" },
    home: { title: "TR3C3 | Café de spécialité et brunch à Miami Platja", description: "Le meilleur café de spécialité et brunch méditerranéen de Miami Platja. Petits-déjeuners soignés, cuisine fraîche et ambiance premium face à la Costa Daurada.", hero: "Le café de spécialité et le brunch qui font craquer Miami Platja.", lead: "Réveillez-vous avec le meilleur café, prolongez le brunch sans regarder l'heure et sentez-vous comme chez vous face à la Costa Daurada. Voici TR3C3.", menuCta: "Voir la carte", mapCta: "Itinéraire", storyTitle: "L'endroit où l'on a toujours envie de revenir.", story: "TR3C3 est né d'une obsession : servir le meilleur café de spécialité de Miami Platja, préparer un brunch vraiment irrésistible et créer un coin où le temps ralentit. Produit frais, mains expertes et âme méditerranéenne dans chaque détail.", menuTitle: "Une carte qui séduit au premier regard.", menuLead: "Café de spécialité, brunch irrésistible et douceurs sucrées et salées pour prolonger le repas.", menuFull: "Découvrir toute la carte", experienceTitle: "Bien plus qu'un café.", experience: "Des matinées sans hâte, des cafés au goût de matin parfait et des douceurs qui prolongent l'après-midi. TR3C3 est le point de rendez-vous de Miami Platja pour se sentir bien, dedans comme dehors.", teamTitle: "L'énergie qui se ressent dans chaque tasse.", team: "Nous sommes une équipe jeune et professionnelle, passionnée d'hospitalité. Le bon café, le brunch avec intention et un accueil chaleureux qui transforme chaque visite en un moment que l'on a envie de revivre.", careersTitle: "Rejoignez-nous", careers: "De l'attitude, de l'énergie et l'envie de prendre soin des gens ? Rejoignez TR3C3 et grandissez avec une équipe qui aime ce qu'elle fait.", careersCta: "Envoyer votre CV", contactTitle: "Rendez-vous à Miami Platja.", address: "Avinguda de Los Ángeles, 13 · 43892 Miami Platja", phone: "Téléphone — à confirmer", hours: "Horaires définitifs — à confirmer", maps: "Ouvrir Google Maps", call: "Appeler", write: "Écrire" },
    menu: { title: "La carte TR3C3", description: "Café de spécialité, boissons fraîches, matcha, brunch, douceurs et plats salés à partager à Miami Platja. Découvrez la carte TR3C3.", intro: "Une carte irrésistible pour chaque moment de la journée.", note: "Prix et disponibilités seront confirmés sur place.", back: "Retour à l'accueil" },
    contact: { title: "Contact et accès | TR3C3 Coffee & Brunch Miami Platja", description: "Où nous trouver et comment venir. Retrouvez TR3C3 à Miami Platja et venez goûter le meilleur café de spécialité et brunch de la Costa Daurada.", heading: "Venez nous rencontrer.", lead: "Une question, une réservation ou simplement l'envie de venir ? Nous sommes là, prêts à vous accueillir.", name: "Nom", email: "E-mail", message: "Message", send: "Envoyer", formNote: "Le formulaire ouvre votre messagerie ; aucune donnée n'est stockée.", careers: "Envie de rejoindre l'équipe ?", careersCta: "Envoyer votre CV" },
    footer: { line: "Café de spécialité, brunch et âme méditerranéenne à Miami Platja.", explore: "Navigation", work: "Rejoignez-nous", guides: "Guides locaux", rights: "Tous droits réservés." },
  },
  de: {
    nav: { home: "Start", concept: "Konzept", menu: "Karte", essence: "Unsere Essenz", contact: "Kontakt", open: "Menü öffnen", close: "Menü schließen", language: "Sprache" },
    home: { title: "TR3C3 | Specialty Coffee und Brunch in Miami Platja", description: "Der beste Specialty Coffee und mediterrane Brunch in Miami Platja. Sorgfältige Frühstücke, frische Küche und Premium-Ambiente an der Costa Daurada. Komm vorbei.", hero: "Der Specialty Coffee und Brunch, in den sich Miami Platja verliebt.", lead: "Wach auf mit dem besten Kaffee, lass den Brunch ohne Blick auf die Uhr laufen und fühl dich wie zu Hause an der Costa Daurada. Das ist TR3C3.", menuCta: "Karte ansehen", mapCta: "Route", storyTitle: "Der Ort, an den man immer zurück will.", story: "TR3C3 entstand aus einer Obsession: den besten Specialty Coffee in Miami Platja zu servieren, einen Brunch zum Verlieben zu kochen und einen Ort zu schaffen, an dem die Zeit langsamer läuft. Frisches Produkt, erfahrene Hände und mediterrane Seele in jedem Detail.", menuTitle: "Eine Karte, in die man sich sofort verliebt.", menuLead: "Specialty Coffee, unwiderstehlicher Brunch und süße wie herzhafte Gelüste für lange Nachmittage.", menuFull: "Ganze Karte entdecken", experienceTitle: "Viel mehr als ein Café.", experience: "Ruhige Frühstücke, Kaffee, der nach perfektem Morgen schmeckt, und Genüsse, die den Nachmittag verlängern. TR3C3 ist der Treffpunkt von Miami Platja, um sich rundum wohlzufühlen.", teamTitle: "Die Energie, die man in jeder Tasse schmeckt.", team: "Wir sind ein junges, professionelles Team mit Liebe zur Gastfreundschaft. Uns treibt guter Kaffee, Brunch mit Absicht und ein herzlicher Service, der jeden Besuch zu einem Moment zum Wiederholen macht.", careersTitle: "Arbeite mit uns", careers: "Du hast Haltung, Energie und Freude daran, dich um Menschen zu kümmern? Komm zu TR3C3 und wachse mit einem Team, das liebt, was es tut.", careersCta: "Lebenslauf senden", contactTitle: "Wir sehen uns in Miami Platja.", address: "Avinguda de Los Ángeles, 13 · 43892 Miami Platja", phone: "Telefon — folgt", hours: "Endgültige Öffnungszeiten — folgen", maps: "Google Maps öffnen", call: "Anrufen", write: "Schreiben" },
    menu: { title: "Die TR3C3 Karte", description: "Specialty Coffee, kalte Getränke, Matcha, Brunch, Süßes und Herzhaftes zum Teilen in Miami Platja. Entdecke die Karte von TR3C3.", intro: "Eine unwiderstehliche Karte für jeden Moment des Tages.", note: "Preise und Verfügbarkeit werden vor Ort bestätigt.", back: "Zur Startseite" },
    contact: { title: "Kontakt und Lage | TR3C3 Coffee & Brunch Miami Platja", description: "Wo wir sind und wie du uns findest. Entdecke TR3C3 in Miami Platja und probiere den besten Specialty Coffee und Brunch an der Costa Daurada.", heading: "Komm vorbei und sag Hallo.", lead: "Eine Frage, eine Reservierung oder einfach neugierig? Wir sind da und freuen uns auf dich.", name: "Name", email: "E-Mail", message: "Nachricht", send: "Anfrage senden", formNote: "Das Formular öffnet dein Mailprogramm; Daten werden nicht gespeichert.", careers: "Teil des Teams werden?", careersCta: "Lebenslauf senden" },
    footer: { line: "Specialty Coffee, Brunch und mediterrane Seele in Miami Platja.", explore: "Navigation", work: "Arbeite mit uns", guides: "Lokale Guides", rights: "Alle Rechte vorbehalten." },
  },
  zh: {
    nav: { home: "首页", concept: "理念", menu: "菜单", essence: "我们的本质", contact: "联系", open: "打开菜单", close: "关闭菜单", language: "语言" },
    home: { title: "TR3C3 | Miami Platja 精品咖啡与早午餐", description: "Miami Platja 最好的精品咖啡与地中海早午餐。精致早餐、新鲜料理与 Costa Daurada 海畔的高级氛围，等你来体验。", hero: "让 Miami Platja 一见倾心的精品咖啡与早午餐。", lead: "用最好的咖啡唤醒一天，不看时间地享受早午餐，在 Costa Daurada 海畔像在家一样自在。这就是 TR3C3。", menuCta: "查看菜单", mapCta: "如何到达", storyTitle: "总让你想再回来的地方。", story: "TR3C3 源于一种执着：做出 Miami Platja 最好的精品咖啡，呈现真正令人期待的早午餐，打造一个让时间慢下来的角落。新鲜食材、专业之手，以及融入每个细节的地中海灵魂。", menuTitle: "一见倾心的菜单。", menuLead: "精品咖啡、令人无法抗拒的早午餐，以及让午后更悠长的甜咸小食。", menuFull: "浏览完整菜单", experienceTitle: "远不止一家咖啡馆。", experience: "悠闲的早餐、尝起来像完美清晨的咖啡，以及延续午后的美味。TR3C3 是 Miami Platja 的相聚之地，让你由内而外感到愉悦。", teamTitle: "每一杯都能尝到的活力。", team: "我们是一支年轻而专业、热爱餐饮服务的团队。好咖啡、用心的早午餐，以及温暖的待客，让每一次到访都值得再来。", careersTitle: "加入我们", careers: "你有态度、有活力，热爱用心待客吗？加入 TR3C3，与热爱所做之事的团队一起成长。", careersCta: "发送简历", contactTitle: "Miami Platja 见。", address: "Avinguda de Los Ángeles, 13 · 43892 Miami Platja", phone: "电话 — 待确认", hours: "最终营业时间 — 待确认", maps: "打开 Google Maps", call: "致电", write: "邮件" },
    menu: { title: "TR3C3 菜单", description: "Miami Platja 的精品咖啡、冷饮、抹茶、早午餐、甜点与可分享的咸食。探索 TR3C3 的菜单。", intro: "适合一天中每个时刻、令人无法抗拒的菜单。", note: "价格与供应情况请以店内为准。", back: "返回首页" },
    contact: { title: "联系与位置 | TR3C3 咖啡与早午餐 Miami Platja", description: "我们的位置与到达方式。在 Miami Platja 找到 TR3C3，来品尝 Costa Daurada 最好的精品咖啡与早午餐。", heading: "来认识我们吧。", lead: "有疑问、想订位，还是单纯好奇？我们就在这里，随时欢迎你。", name: "姓名", email: "邮箱", message: "留言", send: "发送咨询", formNote: "表单会打开你的邮件应用；我们不会存储数据。", careers: "想加入团队？", careersCta: "发送简历" },
    footer: { line: "Miami Platja 的精品咖啡、早午餐与地中海灵魂。", explore: "导航", work: "加入我们", guides: "本地指南", rights: "保留所有权利。" },
  },
  nl: {
    nav: { home: "Home", concept: "Concept", menu: "Menu", essence: "Onze Essentie", contact: "Contact", open: "Menu openen", close: "Menu sluiten", language: "Taal" },
    home: { title: "TR3C3 | Specialty coffee en brunch in Miami Platja", description: "De beste specialty coffee en mediterrane brunch in Miami Platja. Verzorgde ontbijten, verse keuken en een premium sfeer aan de Costa Daurada. Kom langs.", hero: "De specialty coffee en brunch waar Miami Platja voor valt.", lead: "Word wakker met de beste koffie, rek de brunch zonder op de klok te kijken en voel je thuis aan de Costa Daurada. Dit is TR3C3.", menuCta: "Bekijk het menu", mapCta: "Route", storyTitle: "De plek waar je altijd terug wilt komen.", story: "TR3C3 ontstond uit een obsessie: de beste specialty coffee van Miami Platja schenken, een brunch maken waar je echt zin in krijgt en een hoekje creëren waar de tijd trager gaat. Vers product, vakkundige handen en een mediterrane ziel in elk detail.", menuTitle: "Een menu waar je meteen voor valt.", menuLead: "Specialty coffee, onweerstaanbare brunch en zoete en hartige verleidingen voor een lange middag.", menuFull: "Ontdek het volledige menu", experienceTitle: "Veel meer dan een koffiebar.", experience: "Rustige ontbijten, koffie die smaakt naar een perfecte ochtend en lekkers dat de middag verlengt. TR3C3 is de ontmoetingsplek van Miami Platja om je goed te voelen, van binnen en van buiten.", teamTitle: "De energie die je in elke kop proeft.", team: "We zijn een jong, professioneel team met liefde voor gastvrijheid. Goede koffie, brunch met intentie en warme service die elk bezoek tot een moment maakt om te herhalen.", careersTitle: "Werk met ons", careers: "Heb je attitude, energie en passie om voor mensen te zorgen? Sluit je aan bij TR3C3 en groei met een team dat houdt van wat het doet.", careersCta: "Stuur je cv", contactTitle: "Tot ziens in Miami Platja.", address: "Avinguda de Los Ángeles, 13 · 43892 Miami Platja", phone: "Telefoon — volgt", hours: "Definitieve openingstijden — volgen", maps: "Open Google Maps", call: "Bellen", write: "Mailen" },
    menu: { title: "Het TR3C3 menu", description: "Specialty coffee, koude dranken, matcha, brunch, zoet en hartig om te delen in Miami Platja. Ontdek het menu van TR3C3.", intro: "Een onweerstaanbaar menu voor elk moment van de dag.", note: "Prijzen en beschikbaarheid worden in de zaak bevestigd.", back: "Terug naar home" },
    contact: { title: "Contact en locatie | TR3C3 Coffee & Brunch Miami Platja", description: "Waar we zijn en hoe je ons vindt. Vind TR3C3 in Miami Platja en proef de beste specialty coffee en brunch aan de Costa Daurada.", heading: "Kom kennismaken.", lead: "Een vraag, een reservering of gewoon nieuwsgierig? We zijn er, klaar om je te ontvangen.", name: "Naam", email: "E-mail", message: "Bericht", send: "Verstuur", formNote: "Het formulier opent je mailapp; we slaan geen gegevens op.", careers: "Wil je bij het team?", careersCta: "Stuur je cv" },
    footer: { line: "Specialty coffee, brunch en mediterrane ziel in Miami Platja.", explore: "Navigatie", work: "Werk met ons", guides: "Lokale gidsen", rights: "Alle rechten voorbehouden." },
  },
  it: {
    nav: { home: "Home", concept: "Concept", menu: "Menu", essence: "La Nostra Essenza", contact: "Contatti", open: "Apri menu", close: "Chiudi menu", language: "Lingua" },
    home: { title: "TR3C3 | Caffè specialty e brunch a Miami Platja", description: "Il miglior caffè specialty e brunch mediterraneo di Miami Platja. Colazioni curate, cucina fresca e atmosfera premium sulla Costa Daurada. Ti aspettiamo.", hero: "Il caffè specialty e il brunch di cui Miami Platja si innamora.", lead: "Svegliati con il miglior caffè, allunga il brunch senza guardare l'orologio e sentiti a casa sulla Costa Daurada. Questo è TR3C3.", menuCta: "Vedi il menu", mapCta: "Come arrivare", storyTitle: "Quel posto in cui vuoi sempre tornare.", story: "TR3C3 nasce da un'ossessione: servire il miglior caffè specialty di Miami Platja, cucinare un brunch davvero irresistibile e creare un angolo dove il tempo rallenta. Prodotto fresco, mani esperte e anima mediterranea in ogni dettaglio.", menuTitle: "Un menu di cui ti innamori al primo sguardo.", menuLead: "Caffè specialty, brunch irresistibile e tentazioni dolci e salate per allungare il pranzo.", menuFull: "Esplora il menu completo", experienceTitle: "Molto più di una caffetteria.", experience: "Colazioni senza fretta, caffè che sanno di mattina perfetta e dolcezze che allungano il pomeriggio. TR3C3 è il punto d'incontro di Miami Platja per stare bene, dentro e fuori.", teamTitle: "L'energia che senti in ogni tazza.", team: "Siamo un team giovane e professionale, innamorato dell'ospitalità. Ci muovono il buon caffè, il brunch con intenzione e un servizio caloroso che rende ogni visita un momento da ripetere.", careersTitle: "Lavora con noi", careers: "Hai attitudine, energia e passione per prenderti cura delle persone? Unisciti a TR3C3 e cresci con un team che ama ciò che fa.", careersCta: "Invia il CV", contactTitle: "Ci vediamo a Miami Platja.", address: "Avinguda de Los Ángeles, 13 · 43892 Miami Platja", phone: "Telefono — in arrivo", hours: "Orari definitivi — in arrivo", maps: "Apri Google Maps", call: "Chiama", write: "Scrivi" },
    menu: { title: "Il menu TR3C3", description: "Caffè specialty, bevande fredde, matcha, brunch, dolci e piatti salati da condividere a Miami Platja. Scopri il menu di TR3C3.", intro: "Un menu irresistibile per ogni momento della giornata.", note: "Prezzi e disponibilità saranno confermati nel locale.", back: "Torna alla home" },
    contact: { title: "Contatti e posizione | TR3C3 Coffee & Brunch Miami Platja", description: "Dove siamo e come raggiungerci. Trova TR3C3 a Miami Platja e vieni ad assaggiare il miglior caffè specialty e brunch della Costa Daurada.", heading: "Vieni a conoscerci.", lead: "Una domanda, una prenotazione o semplice curiosità? Siamo qui, pronti ad accoglierti.", name: "Nome", email: "Email", message: "Messaggio", send: "Invia richiesta", formNote: "Il modulo apre la tua app email; non memorizziamo i dati.", careers: "Vuoi unirti al team?", careersCta: "Invia il CV" },
    footer: { line: "Caffè specialty, brunch e anima mediterranea a Miami Platja.", explore: "Navigazione", work: "Lavora con noi", guides: "Guide locali", rights: "Tutti i diritti riservati." },
  },
};

export const getTranslation = (lang: Language) => translations[lang];
export const isLanguage = (value: string): value is Language => languages.includes(value as Language);
export type PageKey = "home" | "menu" | "contact";
export const localizedPath = (lang: Language, page: PageKey = "home") => {
  if (page === "menu") return `/${lang}/carta/`;
  if (page === "contact") return `/${lang}/contacto/`;
  return `/${lang}/`;
};
